language: java

jdk:
  - oraclejdk7
#  - openjdk7
#  - openjdk6

env:
  - TERM=dumb

before_install:
  - wget http://services.gradle.org/distributions/gradle-1.8-bin.zip
  - unzip gradle-1.8-bin.zip
  - export GRADLE_HOME=$PWD/gradle-1.8
  - export PATH=$GRADLE_HOME/bin:$PATH

after_success:
  - gradle cobertura
  - gradle coveralls
